### ISSUE TITLE
start_recording service returned with a timeout

### ISSUE THREAD

**Issue by nakai-omer** [NVIDIA-ISAAC-ROS/ros2_benchmark#14]
Hello,

Running a benchmark yields the following error:
`[component_container_mt-1] [ERROR] [1689887945.118569494] [r2b.PlaybackNode]: start_recording service returned with a timeout (0 meessages recorded)`

Some more logs:
```
[component_container_mt-1] [INFO] [1689887909.787793737] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/my_camera/pylon_ros2_camera_node/status", type="pylon_ros2_camera_interfaces/msg/ComponentStatus"
[component_container_mt-1] [INFO] [1689887909.788475075] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/events/write_split", type="rosbag2_interfaces/msg/WriteSplitEvent"
[component_container_mt-1] [INFO] [1689887909.788736408] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/my_camera/pylon_ros2_camera_node/image_raw/compressed", type="sensor_msgs/msg/CompressedImage"
[component_container_mt-1] [INFO] [1689887909.789016222] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/my_camera/pylon_ros2_camera_node/image_rect/theora", type="theora_image_transport/msg/Packet"
[component_container_mt-1] [INFO] [1689887909.789512169] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/clicked_point", type="geometry_msgs/msg/PointStamped"
[component_container_mt-1] [INFO] [1689887909.789880889] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/my_camera/pylon_ros2_camera_node/camera_info", type="sensor_msgs/msg/CameraInfo"
[component_container_mt-1] [INFO] [1689887909.790286193] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/goal_pose", type="geometry_msgs/msg/PoseStamped"
[component_container_mt-1] [INFO] [1689887909.791060411] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/diagnostics", type="diagnostic_msgs/msg/DiagnosticArray"
[component_container_mt-1] [INFO] [1689887909.791433227] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/tag_detections", type="isaac_ros_apriltag_interfaces/msg/AprilTagDetectionArray"
[component_container_mt-1] [INFO] [1689887909.791810197] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/rosout", type="rcl_interfaces/msg/Log"
[component_container_mt-1] [INFO] [1689887909.792192554] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/my_camera/pylon_ros2_camera_node/image_rect/compressedDepth", type="sensor_msgs/msg/CompressedImage"
[component_container_mt-1] [INFO] [1689887909.792572982] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/initialpose", type="geometry_msgs/msg/PoseWithCovarianceStamped"
[component_container_mt-1] [INFO] [1689887909.792906836] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/my_camera/pylon_ros2_camera_node/image_raw", type="sensor_msgs/msg/Image"
[INFO] [1689887915.087159969] [r2b.Controller.Loading]: Requesting to record messages.
[INFO] [1689887915.087475455] [r2b.Controller.Loading]: Requesting to load messages.
[component_container_mt-1] [INFO] [1689887915.087572167] [r2b.PlaybackNode]: start_recording service began
[INFO] [1689887915.087938383] [r2b.Controller.Loading]: Waiting for the recording service to end.
[component_container_mt-1] [INFO] [1689887915.088815581] [rosbag2_storage]: Opened database '/workspaces/isaac_ros-dev/bags/rosbag2_2023_07_20-18_52_43/rosbag2_2023_07_20-18_52_43_0.db3' for READ_ONLY.
[component_container_mt-1] [ERROR] [1689887945.118569494] [r2b.PlaybackNode]: start_recording service returned with a timeout (0 meessages recorded)
[INFO] [1689887945.120868456] [r2b.Controller.Loading]: Requesting to stop loading data.
[INFO] [1689887945.122274272] [r2b.Controller.Loading]: Waiting for the start_loading serevice to end.
FAIL

======================================================================
FAIL: test_benchmark (nakai.TestCustomGraph)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspaces/isaac_ros-dev/src/ros2_benchmark/scripts/nakai.py", line 99, in test_benchmark
    self.run_benchmark()
  File "/workspaces/isaac_ros-dev/install/ros2_benchmark/lib/python3.8/site-packages/ros2_benchmark/ros2_benchmark_test.py", line 852, in run_benchmark
    self.prepare_buffer()
  File "/workspaces/isaac_ros-dev/install/ros2_benchmark/lib/python3.8/site-packages/ros2_benchmark/ros2_benchmark_test.py", line 541, in prepare_buffer
    self.assertTrue(recorded_message_count > 0, 'No message was recorded')
AssertionError: False is not true : No message was recorded
```
We have the following custom benchmark:
```
from launch_ros.actions import ComposableNodeContainer
from launch_ros.descriptions import ComposableNode

from ros2_benchmark import ROS2BenchmarkConfig, ROS2BenchmarkTest

def launch_setup(container_prefix, container_sigterm_timeout):
    """Graph setup for benchmarking your custom graph."""

    # Insert your composable node declarations

    # Required DataLoaderNode
    data_loader_node = ComposableNode(
        name='DataLoaderNode',
        namespace=TestCustomGraph.generate_namespace(),
        package='ros2_benchmark',
        plugin='ros2_benchmark::DataLoaderNode',
        # Insert remappings if necessary
    )

    # Insert your custom preprocessor graph if needed

    # Required PlaybackNode
    playback_node = ComposableNode(
        name='PlaybackNode',
        namespace=TestCustomGraph.generate_namespace(),
        package='ros2_benchmark',
        plugin='ros2_benchmark::PlaybackNode',
        # Revise "data_formats" based on your graph
        parameters=[{
            'data_formats': [
                'sensor_msgs/msg/Image',
                'sensor_msgs/msg/CameraInfo'
            ],
        }],
        # Revise "remapping" based on your graph
        remappings=[
            ('my_camera/pylon_ros2_camera_node/image_rect', 'data_loader/image'),
            ('my_camera/pylon_ros2_camera_node/camera_info', 'data_loader/camera_info'),
        ]
    )

    # Required MonitorNode
    # You can add as many monitor nodes as you need to measure performance
    # for multiple topics.
    monitor_node = ComposableNode(
        name='MonitorNode',
        namespace=TestCustomGraph.generate_namespace(),
        package='ros2_benchmark',
        plugin='ros2_benchmark::MonitorNode',
        parameters=[{
            # Add "monitor_index" parameter to distinguish between various
            # monitor nodes when multiple monitor nodes are used.
            'monitor_data_format': 'isaac_ros_apriltag_interfaces/msg/AprilTagDetectionArray',
        }],
        # Revise "remapping" based on your graph
        remappings=[
            ('tag_detections', 'apriltag_detections')
        ]
    )

    # Required composable node container
    # Insert your composable nodes in the "composable_node_descriptions" list.
    composable_node_container = ComposableNodeContainer(
        name='container',
        namespace=TestCustomGraph.generate_namespace(),
        package='rclcpp_components',
        executable='component_container_mt',
        prefix=container_prefix,
        sigterm_timeout=container_sigterm_timeout,
        composable_node_descriptions=[
            data_loader_node,
            playback_node,
            monitor_node,
            # Insert custom nodes here
        ],
        output='screen'
    )

    return [composable_node_container]

def generate_test_description():
    return TestCustomGraph.generate_test_description_with_nsys(launch_setup)

class TestCustomGraph(ROS2BenchmarkTest):
    """Performance test for your custom graph."""

    # Custom configurations
    config = ROS2BenchmarkConfig(
        # Insert your custom benchmark configurations
        benchmark_name='Nakai Basler Benchmark',
        input_data_path='/workspaces/isaac_ros-dev/bags/rosbag2_2023_07_20-18_52_43',
        publisher_upper_frequency=100.0,
        publisher_lower_frequency=10.0,
        playback_message_buffer_size=10
    )

    def test_benchmark(self):
        self.run_benchmark()
```

**Comment by swapnesh-wani-nvidia** [comment]
It looks like the remappings are not done correctly. Make sure the remappings for DataLoaderNode and PlabackNode are consistent. Have a look at this [section](https://github.com/NVIDIA-ISAAC-ROS/ros2_benchmark#creating-custom-benchmark).
