### ISSUE TITLE
Quick Start step 8 fails

### ISSUE THREAD

**Issue by OsamaThakur** [NVIDIA-ISAAC-ROS/ros2_benchmark#17]
Hello I tried running src/ros2_benchmark/scripts/apriltag_ros_apriltag_node.py && launch_test src/ros2_benchmark/scripts/apriltag_ros_apriltag_graph.py both of them had the same output
```
[INFO] [1694519002.542917470] [r2b.Controller.Loading]: Requesting to stop loading data.
[INFO] [1694519002.543569589] [r2b.Controller.Loading]: Waiting for the start_loading serevice to end.
FAIL

======================================================================
FAIL: test_benchmark (apriltag_ros_apriltag_graph.TestAprilTagGraph)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/ros_ws/src/ros2_benchmark/scripts/apriltag_ros_apriltag_graph.py", line 168, in test_benchmark
    self.run_benchmark()
  File "/root/ros_ws/install/ros2_benchmark/local/lib/python3.10/dist-packages/ros2_benchmark/ros2_benchmark_test.py", line 852, in run_benchmark
    self.prepare_buffer()
  File "/root/ros_ws/install/ros2_benchmark/local/lib/python3.10/dist-packages/ros2_benchmark/ros2_benchmark_test.py", line 541, in prepare_buffer
    self.assertTrue(recorded_message_count > 0, 'No message was recorded')
AssertionError: False is not true : No message was recorded

----------------------------------------------------------------------
Ran 1 test in 35.069s

FAILED (failures=1)
[INFO] [component_container_mt-1]: sending signal 'SIGINT' to process[component_container_mt-1]
[component_container_mt-1] [INFO] [1694519002.846952057] [rclcpp]: signal_handler(signum=2)
[INFO] [component_container_mt-1]: process has finished cleanly [pid 11040]

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

**Comment by swapnesh-wani-nvidia** [comment]
Hello,

Could you confirm that the dataset is loaded properly? From the logs, it looks like no messages were recorded which could point out that the ros bag is not played. Could you share the whole log?

**Comment by OsamaThakur** [comment]
Hi so when I pull the data set here is how they are stored as "r2b_storage_0.db3?Expires=1695205619&Signature=oad6e1kBx0tR8PgpAv4UPeB5sbAWl8U6EcdHowqct0iw60Otd5Z6w9jbw3YPF5IS4HLFHxzVBlyKcipBCj-Ayi8CXOc-1eSGyD-mI-N3CKWj80HQ1R5B9s73V6In6hTJ0J~wPEAAU8EiotE2fkLAaCYxdLBkFw-75eahxI~s5FQny3POrHzRKnlnQ09Kv". I then rename them using "cp <originalname> <.yaml or .db3>".
The complete log 
```
root@osthakur:~/ros_ws# launch_test src/ros2_benchmark/scripts/apriltag_ros_apriltag_node.py
[INFO] [1695203252.362094845] [ROS2BenchmarkTest]: Updating a benchmark config from env: assets_root = /root/ros_ws/src/ros2_benchmark/assets
[INFO] [1695203252.362778599] [r2b]: Waiting 10 seconds for measuring idle system CPU utilization...
[INFO] [launch]: All log files can be found below /root/.ros/log/2023-09-20-09-47-32-362286-osthakur-9211
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [component_container_mt-1]: process started with pid [9224]
[component_container_mt-1] [INFO] [1695203263.672955882] [r2b.container]: Load Library: /root/ros_ws/install/ros2_benchmark/lib/libdata_loader_node.so
[component_container_mt-1] [INFO] [1695203263.676582708] [r2b.container]: Found class: rclcpp_components::NodeFactoryTemplate<ros2_benchmark::DataLoaderNode>
[component_container_mt-1] [INFO] [1695203263.676632702] [r2b.container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<ros2_benchmark::DataLoaderNode>
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/r2b/DataLoaderNode' in container '/r2b/container'
[component_container_mt-1] [INFO] [1695203263.685171275] [r2b.container]: Load Library: /root/ros_ws/install/image_proc/lib/libresize.so
[component_container_mt-1] [INFO] [1695203263.723239456] [r2b.container]: Found class: rclcpp_components::NodeFactoryTemplate<image_proc::ResizeNode>
[component_container_mt-1] [INFO] [1695203263.723274387] [r2b.container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<image_proc::ResizeNode>
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/r2b/PrepResizeNode' in container '/r2b/container'
[component_container_mt-1] [INFO] [1695203263.728682680] [r2b.container]: Load Library: /root/ros_ws/install/ros2_benchmark/lib/libplayback_node.so
[component_container_mt-1] [INFO] [1695203263.729103356] [r2b.container]: Found class: rclcpp_components::NodeFactoryTemplate<ros2_benchmark::PlaybackNode>
[component_container_mt-1] [INFO] [1695203263.729113757] [r2b.container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<ros2_benchmark::PlaybackNode>
[component_container_mt-1] [INFO] [1695203263.731391885] [r2b.PlaybackNode]: Created a generic publisher: topic="/r2b/image"
[component_container_mt-1] [WARN] [1695203263.731565191] [r2b.PrepResizeNode]: New subscription discovered on topic '/r2b/buffer/image', requesting incompatible QoS. No messages will be sent to it. Last incompatible policy: RELIABILITY_QOS_POLICY
[component_container_mt-1] [INFO] [1695203263.731577018] [r2b.PlaybackNode]: Created a generic subscriber: topic="/r2b/buffer/image"
[component_container_mt-1] [INFO] [1695203263.731779360] [r2b.PlaybackNode]: Created a generic publisher: topic="/r2b/camera_info"
[component_container_mt-1] [WARN] [1695203263.731942238] [r2b.PrepResizeNode]: New subscription discovered on topic '/r2b/buffer/camera_info', requesting incompatible QoS. No messages will be sent to it. Last incompatible policy: RELIABILITY_QOS_POLICY
[component_container_mt-1] [INFO] [1695203263.731971187] [r2b.PlaybackNode]: Created a generic subscriber: topic="/r2b/buffer/camera_info"
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/r2b/PlaybackNode' in container '/r2b/container'
[component_container_mt-1] [WARN] [1695203263.732314988] [r2b.PlaybackNode]: New publisher discovered on topic '/r2b/buffer/camera_info', offering incompatible QoS. No messages will be sent to it. Last incompatible policy: RELIABILITY_QOS_POLICY
[component_container_mt-1] [WARN] [1695203263.732358098] [r2b.PlaybackNode]: New publisher discovered on topic '/r2b/buffer/image', offering incompatible QoS. No messages will be sent to it. Last incompatible policy: RELIABILITY_QOS_POLICY
[component_container_mt-1] [INFO] [1695203263.732859669] [r2b.container]: Load Library: /root/ros_ws/install/ros2_benchmark/lib/libmonitor_node.so
[component_container_mt-1] [INFO] [1695203263.733130672] [r2b.container]: Found class: rclcpp_components::NodeFactoryTemplate<ros2_benchmark::MonitorNode>
[component_container_mt-1] [INFO] [1695203263.733140332] [r2b.container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<ros2_benchmark::MonitorNode>
[component_container_mt-1] [INFO] [1695203263.735077860] [r2b.MonitorNode]: [MonitorNode] Starting a monitor node with a service name "start_monitoring0"
[component_container_mt-1] [INFO] [1695203263.735605696] [r2b.MonitorNode]: [MonitorNode] Created a generic type monitor subscriber: topic="/r2b/apriltag_detections"
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/r2b/MonitorNode' in container '/r2b/container'
[component_container_mt-1] [INFO] [1695203263.736420705] [r2b.container]: Load Library: /root/ros_ws/install/apriltag_ros/lib/libAprilTagNode.so
[component_container_mt-1] [INFO] [1695203263.739790659] [r2b.container]: Found class: rclcpp_components::NodeFactoryTemplate<AprilTagNode>
[component_container_mt-1] [INFO] [1695203263.739810190] [r2b.container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<AprilTagNode>
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/r2b/AprilTagNode' in container '/r2b/container'
test_benchmark (apriltag_ros_apriltag_node.TestAprilTagNode) ... [INFO] [1695203268.431079473] [r2b.Controller]: Starting apriltag_ros AprilTagNode Benchmark Benchmark
[INFO] [1695203268.431313110] [r2b.Controller]: Executing pre-benchmark setup
[INFO] [1695203268.431509581] [r2b.Controller]: Buffering test messages
[INFO] [1695203268.432421276] [r2b.Controller.Loading]: Checking input data file...
[INFO] [1695203268.432611942] [r2b.Controller.Loading]:  - Rosbag path = /root/ros_ws/src/ros2_benchmark/assets/datasets/r2b_dataset/r2b_storage/r2b_storage_0.db3
[INFO] [1695203268.432803466] [r2b.Controller.Loading]:  - Compression mode = MESSAGE
[INFO] [1695203268.433005710] [r2b.Controller.Loading]:  - Compression format = zstd
[INFO] [1695203268.433195763] [r2b.Controller.Loading]: Computing input data file hash...
[INFO] [1695203272.487808706] [r2b.Controller.Loading]:  - File hash = "5e8f11201fe10dbac7307a8628553e94"
[INFO] [1695203272.487993630] [r2b.Controller.Loading]:  - File size (bytes) = 3087908864
[INFO] [1695203272.491104218] [r2b.Controller.Loading]: Requesting to initialize the data loader node
[component_container_mt-1] [INFO] [1695203272.491347959] [r2b.DataLoaderNode]: Set the rosbag file to be: /root/ros_ws/src/ros2_benchmark/assets/datasets/r2b_dataset/r2b_storage
[component_container_mt-1] [INFO] [1695203272.500086613] [rosbag2_storage]: Opened database '/root/ros_ws/src/ros2_benchmark/assets/datasets/r2b_dataset/r2b_storage/r2b_storage_0.db3' for READ_ONLY.
[component_container_mt-1] [INFO] [1695203272.500113285] [r2b.DataLoaderNode]: Detected that the rosbag was zstd-message-compressed.
[component_container_mt-1] [INFO] [1695203272.500446013] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/d455_1_right_ir_image", type="sensor_msgs/msg/Image"
[component_container_mt-1] [INFO] [1695203272.500836814] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/pandar_xt_32_0_lidar", type="sensor_msgs/msg/PointCloud2"
[component_container_mt-1] [INFO] [1695203272.501219592] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/tf_static", type="tf2_msgs/msg/TFMessage"
[component_container_mt-1] [INFO] [1695203272.501449949] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/d455_1_rgb_camera_info", type="sensor_msgs/msg/CameraInfo"
[component_container_mt-1] [INFO] [1695203272.501743219] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/data_loader/image", type="sensor_msgs/msg/Image"
[component_container_mt-1] [INFO] [1695203272.501976529] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/d455_1_depth_camera_info", type="sensor_msgs/msg/CameraInfo"
[component_container_mt-1] [INFO] [1695203272.502192691] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/d455_1_depth_image", type="sensor_msgs/msg/Image"
[component_container_mt-1] [INFO] [1695203272.502415282] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/data_loader/camera_info", type="sensor_msgs/msg/CameraInfo"
[component_container_mt-1] [INFO] [1695203272.502588463] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/hawk_0_right_rgb_image", type="sensor_msgs/msg/Image"
[component_container_mt-1] [INFO] [1695203272.502759065] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/d455_1_left_ir_image", type="sensor_msgs/msg/Image"
[component_container_mt-1] [INFO] [1695203272.502936753] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/d455_1_left_ir_camera_info", type="sensor_msgs/msg/CameraInfo"
[component_container_mt-1] [INFO] [1695203272.503104668] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/d455_1_rgb_image", type="sensor_msgs/msg/Image"
[component_container_mt-1] [INFO] [1695203272.503361113] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/d455_1_imu", type="sensor_msgs/msg/Imu"
[component_container_mt-1] [INFO] [1695203272.503553526] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/hawk_0_right_rgb_camera_info", type="sensor_msgs/msg/CameraInfo"
[component_container_mt-1] [INFO] [1695203272.503739257] [r2b.DataLoaderNode]: Created a publisher: topic="/r2b/d455_1_right_ir_camera_info", type="sensor_msgs/msg/CameraInfo"
[INFO] [1695203273.309067312] [r2b.Controller.Loading]: Requesting to record messages.
[component_container_mt-1] [INFO] [1695203273.309443756] [r2b.PlaybackNode]: start_recording service began
[INFO] [1695203273.310111567] [r2b.Controller.Loading]: Requesting to load messages.
[INFO] [1695203273.310410089] [r2b.Controller.Loading]: Waiting for the recording service to end.
[component_container_mt-1] [INFO] [1695203273.311045911] [rosbag2_storage]: Opened database '/root/ros_ws/src/ros2_benchmark/assets/datasets/r2b_dataset/r2b_storage/r2b_storage_0.db3' for READ_ONLY.
[component_container_mt-1] [WARN] [1695203273.728093881] [r2b.PrepResizeNode]: [image_transport] Topics '/r2b/data_loader/image' and '/r2b/image/camera_info' do not appear to be synchronized. In the last 10s:
[component_container_mt-1] 	Image messages received:      0
[component_container_mt-1] 	CameraInfo messages received: 1
[component_container_mt-1] 	Synchronized pairs:           0
[component_container_mt-1] [INFO] [1695203277.105794422] [rosbag2_storage]: Opened database '/root/ros_ws/src/ros2_benchmark/assets/datasets/r2b_dataset/r2b_storage/r2b_storage_0.db3' for READ_ONLY.
[component_container_mt-1] [INFO] [1695203280.815960948] [rosbag2_storage]: Opened database '/root/ros_ws/src/ros2_benchmark/assets/datasets/r2b_dataset/r2b_storage/r2b_storage_0.db3' for READ_ONLY.
[component_container_mt-1] [INFO] [1695203284.521871106] [rosbag2_storage]: Opened database '/root/ros_ws/src/ros2_benchmark/assets/datasets/r2b_dataset/r2b_storage/r2b_storage_0.db3' for READ_ONLY.
[component_container_mt-1] [INFO] [1695203288.229828935] [rosbag2_storage]: Opened database '/root/ros_ws/src/ros2_benchmark/assets/datasets/r2b_dataset/r2b_storage/r2b_storage_0.db3' for READ_ONLY.
[component_container_mt-1] [INFO] [1695203291.999462384] [rosbag2_storage]: Opened database '/root/ros_ws/src/ros2_benchmark/assets/datasets/r2b_dataset/r2b_storage/r2b_storage_0.db3' for READ_ONLY.
[component_container_mt-1] [INFO] [1695203295.806698550] [rosbag2_storage]: Opened database '/root/ros_ws/src/ros2_benchmark/assets/datasets/r2b_dataset/r2b_storage/r2b_storage_0.db3' for READ_ONLY.
[component_container_mt-1] [INFO] [1695203299.399618799] [rosbag2_storage]: Opened database '/root/ros_ws/src/ros2_benchmark/assets/datasets/r2b_dataset/r2b_storage/r2b_storage_0.db3' for READ_ONLY.
[component_container_mt-1] [INFO] [1695203302.909733108] [rosbag2_storage]: Opened database '/root/ros_ws/src/ros2_benchmark/assets/datasets/r2b_dataset/r2b_storage/r2b_storage_0.db3' for READ_ONLY.
[component_container_mt-1] [ERROR] [1695203303.326278409] [r2b.PlaybackNode]: start_recording service returned with a timeout (0 meessages recorded)
[INFO] [1695203303.328893983] [r2b.Controller.Loading]: Requesting to stop loading data.
[INFO] [1695203303.330561840] [r2b.Controller.Loading]: Waiting for the start_loading serevice to end.
FAIL

======================================================================
FAIL: test_benchmark (apriltag_ros_apriltag_node.TestAprilTagNode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/ros_ws/src/ros2_benchmark/scripts/apriltag_ros_apriltag_node.py", line 164, in test_benchmark
    self.run_benchmark()
  File "/root/ros_ws/install/ros2_benchmark/local/lib/python3.10/dist-packages/ros2_benchmark/ros2_benchmark_test.py", line 852, in run_benchmark
    self.prepare_buffer()
  File "/root/ros_ws/install/ros2_benchmark/local/lib/python3.10/dist-packages/ros2_benchmark/ros2_benchmark_test.py", line 541, in prepare_buffer
    self.assertTrue(recorded_message_count > 0, 'No message was recorded')
AssertionError: False is not true : No message was recorded

----------------------------------------------------------------------
Ran 1 test in 34.914s

FAILED (failures=1)
[INFO] [component_container_mt-1]: sending signal 'SIGINT' to process[component_container_mt-1]
[component_container_mt-1] [WARN] [1695203303.728680719] [r2b.PrepResizeNode]: [image_transport] Topics '/r2b/data_loader/image' and '/r2b/image/camera_info' do not appear to be synchronized. In the last 10s:
[component_container_mt-1] 	Image messages received:      0
[component_container_mt-1] 	CameraInfo messages received: 1
[component_container_mt-1] 	Synchronized pairs:           0
[component_container_mt-1] [INFO] [1695203303.776338378] [rclcpp]: signal_handler(signum=2)
[INFO] [component_container_mt-1]: process has finished cleanly [pid 9224]

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```
